CREATE TABLE `creative_performance_feedback` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metaCampaignId` varchar(255) NOT NULL,
	`metaAdSetId` varchar(255),
	`metaAdId` varchar(255),
	`generatedImageUrl` text,
	`headline` text,
	`eyebrow` text,
	`cta` text,
	`format` varchar(50),
	`designSystem` json,
	`imagenPrompt` text,
	`referenceImageUrl` text,
	`impressions` int DEFAULT 0,
	`outboundClicks` int DEFAULT 0,
	`leads` int DEFAULT 0,
	`spend` float DEFAULT 0,
	`ctr` float DEFAULT 0,
	`cpl` float DEFAULT 0,
	`cpm` float DEFAULT 0,
	`conversionRate` float DEFAULT 0,
	`roasOrderVolume` float DEFAULT 0,
	`roasCashCollect` float DEFAULT 0,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`lastUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`performanceDateStart` timestamp,
	`performanceDateEnd` timestamp,
	CONSTRAINT `creative_performance_feedback_id` PRIMARY KEY(`id`)
);
