/**
 * Gemini Imagen Image Generation Service
 * 
 * Uses Gemini Imagen API to generate high-quality images from text prompts.
 * Replaces SDXL for better landing-page-relevant visuals.
 */

import { invokeLLM } from "./llm";
import { ENV } from "./env";
import type { DesignSystem } from "../creative-analyzer";

export interface ImagenConfig {
  prompt: string;
  numberOfImages?: number; // 1-4, default 4
  aspectRatio?: "1:1" | "3:4" | "4:3" | "9:16" | "16:9"; // default "1:1"
  imageSize?: "1K" | "2K"; // default "1K" (only for Standard/Ultra)
  personGeneration?: "dont_allow" | "allow_adult" | "allow_all"; // default "allow_adult"
  referenceImages?: string[]; // URLs of reference images (up to 14) for style consistency
}

export interface ImagenResponse {
  imageUrl: string;
  base64?: string;
}

/**
 * Generate images using Gemini Imagen API
 * 
 * @param config - Image generation configuration
 * @returns Array of generated image URLs
 */
export async function generateImageWithImagen(
  config: ImagenConfig
): Promise<ImagenResponse[]> {
  const {
    prompt,
    numberOfImages = 1,
    aspectRatio = "1:1",
    imageSize = "1K",
    personGeneration = "allow_adult",
    referenceImages = [],
  } = config;

  try {
    // Use Gemini Imagen 4 Standard model
    const model = "imagen-4.0-generate-001";

    // Call Gemini Imagen API via REST
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict`,
      {
        method: "POST",
        headers: {
          "x-goog-api-key": ENV.geminiApiKey,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          instances: [
            {
              prompt,
              // Add reference images if provided (up to 14)
              ...(referenceImages.length > 0 && {
                referenceImages: referenceImages.slice(0, 14).map(url => ({
                  referenceType: 'STYLE', // Use STYLE reference for brand consistency
                  referenceImage: { gcsUri: url }, // Use gcsUri instead of imageUri
                })),
              }),
            },
          ],
          parameters: {
            sampleCount: numberOfImages,
            aspectRatio,
            imageSize,
            personGeneration,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Gemini Imagen API error: ${response.status} - ${errorText}`
      );
    }

    const data = await response.json();

    // Extract image URLs from response
    const predictions = data.predictions || [];
    const images: ImagenResponse[] = [];

    for (const prediction of predictions) {
      // Imagen returns base64-encoded images
      if (prediction.bytesBase64Encoded) {
        // Upload to S3 and get URL
        const imageBuffer = Buffer.from(
          prediction.bytesBase64Encoded,
          "base64"
        );
        const imageUrl = await uploadImageToS3(imageBuffer);
        images.push({ imageUrl, base64: prediction.bytesBase64Encoded });
      } else if (prediction.image) {
        // Some responses might include direct URLs
        images.push({ imageUrl: prediction.image });
      }
    }

    if (images.length === 0) {
      throw new Error("No images generated by Gemini Imagen");
    }

    return images;
  } catch (error) {
    console.error("[Gemini Imagen] Generation failed:", error);
    throw new Error(
      `Gemini Imagen generation failed: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }
}

/**
 * Upload generated image to S3
 */
async function uploadImageToS3(imageBuffer: Buffer): Promise<string> {
  const { storagePut } = await import("../storage");

  // Generate unique filename
  const timestamp = Date.now();
  const randomSuffix = Math.random().toString(36).substring(7);
  const fileKey = `generated-creatives/imagen-${timestamp}-${randomSuffix}.png`;

  // Upload to S3
  const { url } = await storagePut(fileKey, imageBuffer, "image/png");

  return url;
}

/**
 * Build landing-page-aware prompt for Gemini Imagen
 * 
 * This function creates a detailed prompt that focuses on landing page content
 * instead of generic/abstract visuals.
 */
export function buildLandingPageAwarePrompt(params: {
  landingPageContent: string;
  headline: string;
  designSystem: DesignSystem;
  format: "feed" | "story" | "reel";
}): string {
  const { landingPageContent, headline, designSystem, format } = params;

  // Extract key visual elements from landing page
  const visualElements = extractVisualElements(landingPageContent);

  // Build prompt with landing page focus + cinematic quality (in English for better Gemini Imagen results)
  const prompt = `
Create a professional Meta Ads creative image for ${format === "feed" ? "Feed" : format === "story" ? "Story" : "Reel"} format (${
    format === "feed" ? "1:1" : "9:16"
  } aspect ratio).

LANDING PAGE CONTEXT:
${landingPageContent}

VISUAL ELEMENTS TO INCLUDE:
${visualElements}

HEADLINE TO SUPPORT:
"${headline}"

DESIGN SYSTEM:
- Color Palette: ${designSystem.colorPalette.join(', ')}
- Visual Style: ${designSystem.visualStyle}
- Background Style: ${designSystem.backgroundStyle}

CINEMATIC QUALITY (Gemini Best Practices):
- Lighting: Cinematic lighting with subtle rim lights, ${determineLightingStyle(designSystem)}
- Camera Perspective: ${determineCameraPerspective(format, visualElements)}
- Vibe: ${determineVibe(landingPageContent, headline)}
- Depth: Shallow depth of field with bokeh background for premium feel
- Composition: Rule of thirds, leading lines, ${format === "feed" ? "centered subject" : "vertical flow"}

REQUIREMENTS:
- MUST be directly relevant to landing page content
- MUST support the headline message
- NO generic/abstract visuals (no random smartphones, networks, geometric shapes)
- Use landing page color scheme
- Professional, high-quality, marketing-focused
- ${format === "feed" ? "Square composition" : "Vertical composition"}
- Leave space for text overlays (top and bottom)
- NO TEXT IN IMAGE - text will be added separately as overlay

STYLE:
- Modern, clean, professional
- High-quality photography or digital illustration
- Marketing-appropriate (not artistic/abstract)
- Focus on the product/service shown on landing page
- Match the premium aesthetic of the landing page
- Photorealistic rendering with attention to detail
`.trim();

  return prompt;
}

/**
 * Determine lighting style based on design system
 */
function determineLightingStyle(designSystem: DesignSystem): string {
  const bgStyle = designSystem.backgroundStyle.toLowerCase();
  const visualStyle = designSystem.visualStyle.toLowerCase();
  
  if (bgStyle.includes('dark') || bgStyle.includes('night')) {
    return 'dramatic shadows with neon accents, moody atmosphere';
  }
  if (bgStyle.includes('gradient') || visualStyle.includes('modern')) {
    return 'soft gradient lighting, contemporary feel';
  }
  if (visualStyle.includes('premium') || visualStyle.includes('luxury')) {
    return 'golden hour warm tones, premium aesthetic';
  }
  return 'natural daylight, clean and bright';
}

/**
 * Determine camera perspective based on format and visual elements
 */
function determineCameraPerspective(format: string, visualElements: string): string {
  if (visualElements.includes('dashboard') || visualElements.includes('interface')) {
    return 'Slightly elevated angle (15°), professional workspace view';
  }
  if (visualElements.includes('book') || visualElements.includes('guide')) {
    return 'Low angle hero shot, emphasizing importance and value';
  }
  if (format === 'feed') {
    return 'Eye-level perspective, direct and engaging';
  }
  return 'Dynamic angle with depth, vertical composition optimized';
}

/**
 * Determine vibe based on landing page content and headline
 */
function determineVibe(landingPageContent: string, headline: string): string {
  const content = (landingPageContent + ' ' + headline).toLowerCase();
  
  if (content.includes('premium') || content.includes('exclusive') || content.includes('luxury')) {
    return 'Premium, exclusive, aspirational';
  }
  if (content.includes('fast') || content.includes('quick') || content.includes('sofort') || content.includes('jetzt')) {
    return 'Energetic, urgent, action-oriented';
  }
  if (content.includes('simple') || content.includes('easy') || content.includes('einfach')) {
    return 'Approachable, friendly, confidence-building';
  }
  if (content.includes('professional') || content.includes('business') || content.includes('enterprise')) {
    return 'Professional, trustworthy, corporate';
  }
  return 'Modern, innovative, forward-thinking';
}

/**
 * Extract visual elements from landing page content
 */
function extractVisualElements(landingPageContent: string): string {
  // Simple keyword extraction
  const keywords = [
    "dashboard",
    "analytics",
    "leads",
    "marketing",
    "automation",
    "funnel",
    "conversion",
    "campaign",
    "ads",
    "meta",
    "facebook",
    "instagram",
    "social media",
    "dca",
    "dynamic creative",
    "performance",
    "metrics",
    "roi",
    "roas",
  ];

  const found = keywords.filter((keyword) =>
    landingPageContent.toLowerCase().includes(keyword)
  );

  if (found.length === 0) {
    return "Professional business/marketing visuals";
  }

  // Build visual description
  const visualDescriptions: string[] = [];

  if (found.includes("dashboard") || found.includes("analytics")) {
    visualDescriptions.push(
      "Marketing dashboard with charts and metrics"
    );
  }

  if (found.includes("leads") || found.includes("conversion")) {
    visualDescriptions.push("Lead generation funnel visualization");
  }

  if (found.includes("meta") || found.includes("facebook") || found.includes("ads")) {
    visualDescriptions.push("Meta Ads interface or campaign visuals");
  }

  if (found.includes("dca") || found.includes("dynamic creative")) {
    visualDescriptions.push("Dynamic creative optimization visuals");
  }

  return visualDescriptions.join(", ") || "Professional marketing visuals";
}
