/**
 * Gemini Imagen Image Generation Service
 * 
 * Uses Gemini Imagen API to generate high-quality images from text prompts.
 * Replaces SDXL for better landing-page-relevant visuals.
 */

import { invokeLLM } from "./llm";
import { ENV } from "./env";
import type { DesignSystem } from "../creative-analyzer";

export interface ImagenConfig {
  prompt: string;
  numberOfImages?: number; // 1-4, default 4
  aspectRatio?: "1:1" | "3:4" | "4:3" | "9:16" | "16:9"; // default "1:1"
  imageSize?: "1K" | "2K"; // default "1K" (only for Standard/Ultra)
  personGeneration?: "dont_allow" | "allow_adult" | "allow_all"; // default "allow_adult"
  referenceImages?: string[]; // URLs of reference images (up to 14) for style consistency
}

export interface ImagenResponse {
  imageUrl: string;
  base64?: string;
}

/**
 * Generate images using Gemini Imagen API
 * 
 * @param config - Image generation configuration
 * @returns Array of generated image URLs
 */
export async function generateImageWithImagen(
  config: ImagenConfig
): Promise<ImagenResponse[]> {
  const {
    prompt,
    numberOfImages = 1,
    aspectRatio = "1:1",
    imageSize = "1K",
    personGeneration = "allow_adult",
    referenceImages = [],
  } = config;

  try {
    // Use Gemini Imagen 4 Standard model
    const model = "imagen-4.0-generate-001";

    // Call Gemini Imagen API via REST
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict`,
      {
        method: "POST",
        headers: {
          "x-goog-api-key": ENV.geminiApiKey,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          instances: [
            {
              prompt,
              // Add reference images if provided (up to 14)
              ...(referenceImages.length > 0 && {
                referenceImages: referenceImages.slice(0, 14).map(url => ({
                  referenceType: 'STYLE', // Use STYLE reference for brand consistency
                  referenceImage: { gcsUri: url }, // Use gcsUri instead of imageUri
                })),
              }),
            },
          ],
          parameters: {
            sampleCount: numberOfImages,
            aspectRatio,
            imageSize,
            personGeneration,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Gemini Imagen API error: ${response.status} - ${errorText}`
      );
    }

    const data = await response.json();

    // Extract image URLs from response
    const predictions = data.predictions || [];
    const images: ImagenResponse[] = [];

    for (const prediction of predictions) {
      // Imagen returns base64-encoded images
      if (prediction.bytesBase64Encoded) {
        // Upload to S3 and get URL
        const imageBuffer = Buffer.from(
          prediction.bytesBase64Encoded,
          "base64"
        );
        const imageUrl = await uploadImageToS3(imageBuffer);
        images.push({ imageUrl, base64: prediction.bytesBase64Encoded });
      } else if (prediction.image) {
        // Some responses might include direct URLs
        images.push({ imageUrl: prediction.image });
      }
    }

    if (images.length === 0) {
      throw new Error("No images generated by Gemini Imagen");
    }

    return images;
  } catch (error) {
    console.error("[Gemini Imagen] Generation failed:", error);
    throw new Error(
      `Gemini Imagen generation failed: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }
}

/**
 * Upload generated image to S3
 */
async function uploadImageToS3(imageBuffer: Buffer): Promise<string> {
  const { storagePut } = await import("../storage");

  // Generate unique filename
  const timestamp = Date.now();
  const randomSuffix = Math.random().toString(36).substring(7);
  const fileKey = `generated-creatives/imagen-${timestamp}-${randomSuffix}.png`;

  // Upload to S3
  const { url } = await storagePut(fileKey, imageBuffer, "image/png");

  return url;
}

/**
 * Build landing-page-aware prompt for Gemini Imagen
 * 
 * This function creates a detailed prompt that focuses on landing page content
 * instead of generic/abstract visuals.
 */
export function buildLandingPageAwarePrompt(params: {
  landingPageContent: string;
  headline: string;
  designSystem: DesignSystem;
  format: "feed" | "story" | "reel";
  eyebrowText?: string;
  ctaText?: string;
}): string {
  const { landingPageContent, headline, designSystem, format, eyebrowText, ctaText } = params;

  // Extract key visual elements from landing page
  const visualElements = extractVisualElements(landingPageContent);

  // Build prompt with landing page focus + cinematic quality (in English for better Gemini Imagen results)
  const prompt = `
Create a professional Meta Ads creative image for ${format === "feed" ? "Feed" : format === "story" ? "Story" : "Reel"} format (${
    format === "feed" ? "1:1" : "9:16"
  } aspect ratio).

LANDING PAGE CONTEXT:
${landingPageContent}

VISUAL ELEMENTS TO INCLUDE:
${visualElements}

HEADLINE TO SUPPORT:
"${headline}"

DESIGN SYSTEM:
- Color Palette: ${designSystem.colorPalette.join(', ')}
- Visual Style: ${designSystem.visualStyle}
- Background Style: ${designSystem.backgroundStyle}

CINEMATIC QUALITY (Gemini Best Practices):
- Lighting: Cinematic lighting with subtle rim lights, ${determineLightingStyle(designSystem)}
- Camera Perspective: ${determineCameraPerspective(format, visualElements)}
- Vibe: ${determineVibe(landingPageContent, headline)}
- Depth: Shallow depth of field with bokeh background for premium feel
- Composition: Rule of thirds, leading lines, ${format === "feed" ? "centered subject" : "vertical flow"}

REQUIREMENTS:
- MUST be directly relevant to landing page content and show REAL product/service
- MUST support the headline message
- ABSOLUTELY NO: dashboards, analytics screens, 3D geometric objects, abstract shapes, floating UI elements, timeline graphics
- YES: Real people, real products, real environments, tangible results
- Use landing page color scheme
- Professional, high-quality, marketing-focused
- Photorealistic or high-quality illustration (NOT 3D renders)
- ${format === "feed" ? "Square composition" : "Vertical composition"}
- Leave space for text overlays (top 20%, center 40%, bottom 20%)
  * Top area: reserved for eyebrow text
  * Center area: reserved for main headline
  * Bottom area: reserved for CTA button
- DO NOT include any text, letters, or words in the generated image
- Text will be added separately as professional overlays
- Ensure background has good contrast areas for text readability

STYLE:
- Modern, clean, professional
- High-quality photography or digital illustration
- Marketing-appropriate (not artistic/abstract)
- Focus on the product/service shown on landing page
- Match the premium aesthetic of the landing page
- Photorealistic rendering with attention to detail
`.trim();

  return prompt;
}

/**
 * Determine lighting style based on design system
 * ALWAYS uses dark/neon cyberpunk aesthetic for user's brand
 */
function determineLightingStyle(designSystem: DesignSystem): string {
  // ALWAYS use dark background with neon accents for user's brand
  const bgStyle = designSystem.backgroundStyle.toLowerCase();
  const visualStyle = designSystem.visualStyle.toLowerCase();
  
  if (visualStyle.includes('premium') || visualStyle.includes('luxury')) {
    return 'dark background with purple/pink neon glow, dramatic shadows, premium cyberpunk aesthetic';
  }
  if (bgStyle.includes('tech') || bgStyle.includes('digital')) {
    return 'dark background with blue/green neon highlights, futuristic tech lighting, high contrast';
  }
  // Default: dark/neon cyberpunk style
  return 'dark background (#000000) with bright neon accents (green #26FF00, purple #5E259F), cyberpunk lighting, high contrast, moody atmosphere';
}

/**
 * Determine camera perspective based on format and visual elements
 */
function determineCameraPerspective(format: string, visualElements: string): string {
  if (visualElements.includes('dashboard') || visualElements.includes('interface')) {
    return 'Slightly elevated angle (15°), professional workspace view';
  }
  if (visualElements.includes('book') || visualElements.includes('guide')) {
    return 'Low angle hero shot, emphasizing importance and value';
  }
  if (format === 'feed') {
    return 'Eye-level perspective, direct and engaging';
  }
  return 'Dynamic angle with depth, vertical composition optimized';
}

/**
 * Determine vibe based on landing page content and headline
 * ALWAYS uses dark/neon cyberpunk aesthetic for user's brand
 */
function determineVibe(landingPageContent: string, headline: string): string {
  const content = (landingPageContent + ' ' + headline).toLowerCase();
  
  // ALWAYS use dark/neon cyberpunk vibe for user's brand
  if (content.includes('premium') || content.includes('exclusive') || content.includes('luxury')) {
    return 'Dark, premium cyberpunk aesthetic, exclusive futuristic vibe, high-tech luxury, neon-lit sophistication';
  }
  if (content.includes('fast') || content.includes('quick') || content.includes('sofort') || content.includes('jetzt')) {
    return 'Energetic dark theme, dynamic neon elements, fast-paced cyberpunk, urgent futuristic atmosphere';
  }
  if (content.includes('simple') || content.includes('easy') || content.includes('einfach')) {
    return 'Clean dark design, minimal neon accents, accessible futuristic style, approachable cyberpunk';
  }
  if (content.includes('professional') || content.includes('business') || content.includes('enterprise')) {
    return 'Professional dark aesthetic, corporate cyberpunk, trustworthy futuristic design, business-grade neon tech';
  }
  return 'Dark, futuristic, cyberpunk, high-tech, neon-lit, modern, innovative, 3D rendered';
}

/**
 * Extract visual elements from landing page content
 * AVOID generic dashboards/3D objects - focus on REAL product/service
 */
function extractVisualElements(landingPageContent: string): string {
  const content = landingPageContent.toLowerCase();
  
  // Priority 1: Look for REAL products/services mentioned
  const productKeywords = [
    { keyword: "book", visual: "Professional book cover or guide on desk, premium lighting" },
    { keyword: "course", visual: "Online learning environment, student success, laptop with course content" },
    { keyword: "software", visual: "Clean software interface on laptop, professional workspace" },
    { keyword: "coaching", visual: "Professional coach in modern office, confident expert" },
    { keyword: "consulting", visual: "Business consultant presenting strategy, professional setting" },
    { keyword: "agency", visual: "Marketing agency team working, creative workspace" },
    { keyword: "service", visual: "Professional service delivery, satisfied client" },
    { keyword: "product", visual: "Product showcase, premium presentation" },
    { keyword: "tool", visual: "Professional tool in use, productivity improvement" },
  ];
  
  for (const { keyword, visual } of productKeywords) {
    if (content.includes(keyword)) {
      return visual;
    }
  }
  
  // Priority 2: Look for outcome/benefit visuals
  if (content.includes("lead") || content.includes("customer")) {
    return "Happy business owner reviewing successful results on laptop, professional office";
  }
  if (content.includes("growth") || content.includes("scale")) {
    return "Growing business, upward trend, professional success";
  }
  if (content.includes("time") || content.includes("save")) {
    return "Relaxed professional with free time, work-life balance, modern workspace";
  }
  
  // Fallback: Generic professional scene (NO dashboards/3D objects)
  return "Professional business person working confidently in modern office, clean minimal aesthetic, natural lighting";
}
